copy_data_dict["full_name"] = i[]
copy_data_dict["short_name"] = i[]
copy_data_dict["version"] = i[]
copy_data_dict["finish_time"] = i[]
copy_data_dict["push_time"] = i[]
copy_data_dict["push_addr"] = i[]

copy_data_dict["owner_name"] = i[]
copy_data_dict["owner_type"] = i[]
copy_data_dict["owner_id_type"] = i[]
copy_data_dict["owner_code"] = i[]
copy_data_dict["owner_province"] = i[]

copy_data_dict["hardware_env"] = i[]
copy_data_dict["software_env"] = i[]
copy_data_dict["language"] = i[]
copy_data_dict["row_length"] = i[]
copy_data_dict["main_desc"] = i[]

copy_data_dict["proposer_name"] = i[]
copy_data_dict["proposer_addr"] = i[]
copy_data_dict["proposer_linkman_name"] = i[]
copy_data_dict["proposer_email_addr"] = i[]
copy_data_dict["proposer_tel"] = i[]
copy_data_dict["proposer_area_code"] = i[]
copy_data_dict["proposer_phone"] = i[]